version: "3"

services:
    gitea:
        image: gitea/gitea:latest
        container_name: gitea
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - RUN_MODE=prod
        restart: always
        volumes:
            - ./gitea:/data
        ports:
            - "3000:3000"

    drone:
        image: drone/drone:latest
        container_name: drone
        environment:
            - DRONE_GITEA_SERVER=http://gitea:3000
            - DRONE_GIT_ALWAYS_AUTH=false
            - DRONE_RUNNER_CAPACITY=2
            - DRONE_SERVER_PROTO=http
            - DRONE_SERVER_HOST=localhost
            - DRONE_TLS_AUTOCERT=false
            - DRONE_USER_CREATE=username:user,admin:true,token:1234567890abcdef
        restart: always
        ports:
            - "3001:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./drone:/data

