#!/bin/zsh

local no_inet_label="<span color=\"#D01B24\">轢</span> No internet"

local def_interface="$(ip route | awk '/^default/ { print $5 }')"
local dev_label=''

# Если в интерфейсах по умолчанию есть LAN-интерфейс
if [ -n "$(echo ${def_interface} | grep '^e.*')" ]; then
    # Если он поднят
    if [ "$(cat /sys/class/net/e*/operstate)" = 'up' ]; then
        dev_label="${dev_label}<span color=\"#A7D32C\">歷</span>"
    fi
fi

# Если в интерфейсах по умолчанию есть Wireless-интерфейс
if [ -n "$(echo ${def_interface} | grep '^w.*')" ]; then
    # Если он поднят
    if [ "$(cat /sys/class/net/w*/operstate)" = 'up' ]; then
        local wifi_quality="$(grep "^\s*w" /proc/net/wireless | awk '{ print int($3 * 100 / 70) "%" }')"
        dev_label="${dev_label} <span color=\"#6EADDF\"> ${wifi_quality}</span>"
    fi
fi

# Если есть хотя бы одно подключение, то определяем внешний IP и страну
if [ -n "$dev_label" ]; then
    local addr="$(curl ifconfig.me 2>/dev/null)"
    local country="$(geoiplookup 128.0.138.61 2>/dev/null | sed 's/.*: //' | sed 's/,.*//')" && addr="$addr <span color=\"#FF8B25\">($country)</span>"

    echo "${dev_label} : ${addr}"
else
    # Все плохо: кабель обрубили :(
    echo $no_inet_label
fi
