#!/bin/zsh

case $BLOCK_BUTTON in
    1) i3-nagbar -t warning \
        -m 'Вы нажали кнопку перезагрузки компьютера. Вы действительно хотите ПЕРЕЗАГРУЗИТЬ его?' \
        -b 'Да, перезагрузить' 'reboot' >/dev/null
esac