require('options')
require('packages')
require('theme')
require('key-mappings')

require('plugins/common')
require('plugins/lualine')
require('plugins/bufferline')
require('plugins/nvim-tree')
require('plugins/nvim-treesitter')
require('plugins/nvim-lspconfig')
require('plugins/nvim-cmp')
require('plugins/luasnip')
require('plugins/telescope')
require('plugins/nvim-dap')
require('plugins/neovim-cmake')

